project_id = "kyzbzcdkgggxhakwaqmb"

[functions.chargebee-webhook]
verify_jwt = false

[functions.create-chargebee-checkout]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.generate-billionaire-data]
verify_jwt = false
